blank_issues_enabled: false
contact_links:
  - name: Bayat Forums
    url: https://forums.bayat.io
    about: Please ask and answer questions here.
  - name: Discussions
    url: https://www.example.com
    about: Use discussions bouard to talk with community and exchange information.
